name: hhu_assist
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  objectbox: ^1.7.2
  objectbox_flutter_libs: any
  permission_handler: ^10.2.0
  spreadsheet_decoder: ^2.1.1
  snippet_coder_utils: ^1.0.13
  quickalert: ^1.0.1
  qr_code_scanner: ^1.0.1
  location: ^4.4.0
  syncfusion_flutter_xlsio: ^20.4.52-beta
  http: ^0.13.5
  flutter_launcher_icons: ^0.12.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.7
  path_provider: ^2.0.13
  dropdown_search: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any

flutter:

  uses-material-design: true

  assets:
    - assets/placeholder_350x250.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # change image and run the following \> flutter pub run flutter_launcher_icons
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"